# Generated by Django 4.2.27 on 2026-02-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Unique URL friendly identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload gallery image', upload_to='gallery/')),
                ('alt_text', models.CharField(help_text='Alternative text for accessibility', max_length=200)),
                ('caption', models.TextField(blank=True, help_text='Image caption')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the image is visible in the gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='Unique URL friendly identifier', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title', max_length=255)),
                ('slug', models.SlugField(help_text='Unique URL friendly identifier', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description for post cards')),
                ('content', models.JSONField(help_text='Rich content from Lexical editor in JSON format')),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the post', null=True, upload_to='posts/featured/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alternative text for featured image', max_length=200)),
                ('video_url', models.URLField(blank=True, help_text='Video URL if post has a video instead of image')),
                ('author', models.CharField(default='Admin', help_text='Author name', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Post publication status', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='Date and time when post was published', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(help_text='Select categories for this post', related_name='posts', to='api.category')),
                ('gallery_images', models.ManyToManyField(blank=True, help_text='Select gallery images to include in post', related_name='posts', to='api.galleryimage')),
                ('tags', models.ManyToManyField(blank=True, help_text='Select tags for this post', related_name='posts', to='api.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
