# Generated by Django 4.2.27 on 2026-02-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(blank=True, help_text='HTML representation of content for display purposes'),
        ),
    ]
