# Generated by Django 4.2.27 on 2026-02-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.URLField(help_text='Cloudinary image URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.URLField(blank=True, help_text='Cloudinary featured image URL', max_length=500),
        ),
    ]
