# Generated by Django 4.2.27 on 2026-02-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_galleryimage_image_alter_post_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(help_text='Cloudinary image URL', max_length=500)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('caption', models.TextField(blank=True, help_text='Image caption')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within post')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Post Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='gallery_images',
        ),
        migrations.AddField(
            model_name='post',
            name='post_images',
            field=models.ManyToManyField(blank=True, help_text='Images to display within this post', related_name='posts', to='api.postimage'),
        ),
    ]
